# Generated by Django 5.1.4 on 2025-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default=None, null=True, verbose_name='Пол'),
        ),
    ]
